### ISSUE TITLE
Update post-treatment LTFU variables

### ISSUE THREAD

**Issue by JayAchar** [JayAchar/tbmstr#121]
# Tasks

- [x] Confirm calculate of follow-up time is correct
- [x] Confirm that post-treatment follow-up days is calculated and correct
- [x] Calculate variables for post-treatment LTFU status at different time points

**Comment by JayAchar** [comment]
# Outcome

On closer inspection, attendence at the 12 month follow up appointment was used as the definition of being in follow-up at the end of the study. This should have been changed to fu_days >= 365 or something, but the difference in the classification was so close that it didn't matter.
