### ISSUE TITLE
Add random effects to analysis

### ISSUE THREAD

**Issue by JayAchar** [JayAchar/tbmstr#70]
https://myweb.uiowa.edu/pbreheny/7210/f15/notes/10-29.pdf
https://cran.r-project.org/web/packages/coxme/vignettes/coxme.pdf
https://doi.org/10.1111/insr.12214

**Comment by JayAchar** [comment]
# Tasks

- [ ] Create LR test function 
- [ ] Choose appropriate method for incorporating random effects
- [ ] Add interactive _targets step for developing a model

**Comment by JayAchar** [comment]
# Method choice

The frailty approach adds a random intercept estimate to the model and appears to fit the data as well as any other. This can be implemented with the `coxme` package or directly with the survival package using the `frailty` function.
