### ISSUE TITLE
Update manual data adjustments

### ISSUE THREAD

**Issue by JayAchar** [JayAchar/tbmstr#81]
# Tasks

- [x] Move original adjustments out of package and into step function
- [x] Create package function to apply modifications
- [x] Import modification files as new step including dependency
- [x] Create custom step function for adjusting outcomes
